version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: booking-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: booking-db
      MYSQL_USER: huuloc2026
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql   # Mount file SQL vào thư mục initdb
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
